sudo: required
language: ruby
bundler_args: --without benchmarks development
before_install:
  - gem --version
  - bash .travis_setup.sh
os:
  - linux
addons:
  hosts:
    - mysql2gem.example.com
rvm:
  - 2.3.0
  - 2.2
  - 2.1
  - 2.0.0
  - 1.9.3
  - 1.8.7
  - ree
  - rbx-2
  - ruby-head
matrix:
  include:
    - rvm: 2.0.0
      env: DB=mariadb55
      addons:
         mariadb: 5.5
         hosts:
           - mysql2gem.example.com
    - rvm: 2.0.0
      env: DB=mariadb10.0
      addons:
         mariadb: 10.0
         hosts:
           - mysql2gem.example.com
    - rvm: 2.0.0
      env: DB=mariadb10.1
      addons:
         mariadb: 10.1
         hosts:
           - mysql2gem.example.com
    - rvm: 2.0.0
      env: DB=mysql57
    - rvm: 2.0.0
      env: DB=mysql55
      os: osx
  allow_failures:
    - rvm: ruby-head
