language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ree
  - rbx-18mode
  - rbx-19mode
  - ruby-head
matrix:
  allow_failures:
    - rvm: rbx-18mode
    - rvm: rbx-19mode
bundler_args: --without benchmarks
script:
  - bundle exec rake
  - bundle exec rspec
