language: ruby
bundler_args: --without benchmarks development
before_install:
  - gem --version
  - bash .travis_setup.sh
  - mysqld --version
  - mysql -u $USER -e "CREATE DATABASE IF NOT EXISTS test"
os:
  - linux
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - ree
  - rbx-2
matrix:
  include:
    - rvm: 2.0.0
      env: DB=mariadb55
    - rvm: 2.0.0
      env: DB=mariadb10
    - rvm: 2.0.0
      env: DB=mysql57
    - rvm: 2.0.0
      os: osx
