language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ree
  - rbx-18mode
  - rbx-19mode
  - rbx-20mode
bundler_args: --without benchmarks
allow_failures:
  - rvm: rbx-19mode
  - rvm: rbx-20mode
script:
  - bundle exec rake
  - bundle exec rspec
