language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0-preview2
  - ree
  - rbx
matrix:
  allow_failures:
    - rvm: 2.1.0-preview2
env: RBXOPT=-Xgc.honor_start=true
bundler_args: --without benchmarks
script:
  - bundle exec rake
  - bundle exec rspec
